name: "godot gut test"
on: push

jobs:
  execute-gut:
    name: Run GUT tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import Headless
        run: |
          godot --headless --import

      - name: Docker test
        uses: ceceppa/godot-gut-ci@main
